---
- name: Print variable
  command: echo {{ variable }}
  register: result

- debug: var=result

- name: Print variable
  command: echo {{ dico['field1'] }}
  register: result2

- debug: var=result2

- name: Print variable
  command: echo {{ variable_prompt }}
  register: result3

- debug: var=result3

- name: Print variable
  command: echo {{ cmd_var }}
  register: result4

- debug: var=result4
